/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ItfUser;

import CtrDatabase.DBConnection;
import CtrObj.Ban;
import ItfLogin.Frame_Login;
import CtrObj.User;
import ItfUser.PanelBanHang.PanelBanHang;
import ItfUser.PanelKho.PanelKho;
import ItfUser.PanelThongKe.PanelThongKe;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author Zoro
 */
public class Frame_User extends javax.swing.JFrame {

    /**
     * Creates new form Frame_User
     */
    User user;
    private SimpleDateFormat sdfToDay;
    private java.util.Date toDay;
    private Timer timerNgayGio;
    public static int soBanActive;
    PanelBanHang panelBanHang = new PanelBanHang();
    PanelKho panelKho = new PanelKho();
    PanelThongKe panelThongKe = new PanelThongKe();
    public static int idUser = 2;
    
    public Frame_User() {
        initComponents();
        KhoiTao();
    }

    public Frame_User(User user) {
        this.user = user;
        initComponents();
        KhoiTao();
    }

    private void KhoiTao() {
        //Khởi tạo các Panel
        this.getContentPane().add(panelBanHang);
        this.getContentPane().add(panelKho);
        this.getContentPane().add(panelThongKe);
        panelBanHang.setBounds(0, 85, 1280, 630);
        panelThongKe.setBounds(0, 85, 1280, 630);
        panelKho.setBounds(0, 85, 1280, 630);
        panelThongKe.setVisible(false);
        panelKho.setVisible(false);
        panelBanHang.setVisible(false);
//        idUser = user.getIdUser();
        
        //Tên đăng nhập
//        jlbTenDangNhap.setText(user.getUserName());

        //Ngày giờ
        TimerTick();

        //Số bàn active
        try {
            soBanActive = DBConnection.getSoBanActive();
        } catch (SQLException ex) {
            Logger.getLogger(Frame_User.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Frame_User.class.getName()).log(Level.SEVERE, null, ex);
        }
        jlbSoBanActive.setText("Đang phục vụ: " + String.valueOf(soBanActive) + " bàn");

        
    }

    private void TimerTick() {
        timerNgayGio = new Timer(1, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                toDay = new java.util.Date(System.currentTimeMillis());
                sdfToDay = new SimpleDateFormat("dd/MM/yyyy   HH:mm:ss ");
                jlbNgayGio.setText(sdfToDay.format(toDay.getTime()));
            }
        });
        timerNgayGio.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnBanHang = new javax.swing.JButton();
        jbtnKho = new javax.swing.JButton();
        jbtnThongKe = new javax.swing.JButton();
        jbtnThoat = new javax.swing.JButton();
        jbtnDangXuat = new javax.swing.JButton();
        jlbTenDangNhap = new javax.swing.JLabel();
        jlbNgayGio = new javax.swing.JLabel();
        jlbSoBanActive = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 100));

        jbtnBanHang.setBackground(new java.awt.Color(255, 255, 204));
        jbtnBanHang.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jbtnBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/staff.png"))); // NOI18N
        jbtnBanHang.setText("Bán Hàng  ");
        jbtnBanHang.setBorder(null);
        jbtnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBanHangActionPerformed(evt);
            }
        });

        jbtnKho.setBackground(new java.awt.Color(255, 255, 204));
        jbtnKho.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jbtnKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/staff.png"))); // NOI18N
        jbtnKho.setText("Kho  ");
        jbtnKho.setBorder(null);
        jbtnKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKhoActionPerformed(evt);
            }
        });

        jbtnThongKe.setBackground(new java.awt.Color(255, 255, 204));
        jbtnThongKe.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jbtnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/staff.png"))); // NOI18N
        jbtnThongKe.setText("Thống Kê  ");
        jbtnThongKe.setBorder(null);
        jbtnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThongKeActionPerformed(evt);
            }
        });

        jbtnThoat.setBackground(new java.awt.Color(255, 255, 204));
        jbtnThoat.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jbtnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/staff.png"))); // NOI18N
        jbtnThoat.setText("Thoát  ");
        jbtnThoat.setBorder(null);
        jbtnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThoatActionPerformed(evt);
            }
        });

        jbtnDangXuat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtnDangXuat.setText("Đăng xuất");
        jbtnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDangXuatActionPerformed(evt);
            }
        });

        jlbTenDangNhap.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbTenDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTenDangNhap.setText("$Tên_đăng_nhập");

        jlbNgayGio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbNgayGio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNgayGio.setText("$Ngày");
        jlbNgayGio.setPreferredSize(new java.awt.Dimension(220, 17));

        jlbSoBanActive.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbSoBanActive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbSoBanActive.setText("$Số_bàn_active");
        jlbSoBanActive.setPreferredSize(new java.awt.Dimension(220, 17));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jbtnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnKho, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jlbSoBanActive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNgayGio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jlbTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbNgayGio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbTenDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbSoBanActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnKho, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 640, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbtnThoatActionPerformed

    private void jbtnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBanHangActionPerformed
        // TODO add your handling code here:
        panelThongKe.setVisible(false);
        panelKho.setVisible(false);

        panelBanHang.setVisible(true);
    }//GEN-LAST:event_jbtnBanHangActionPerformed

    private void jbtnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThongKeActionPerformed
        // TODO add your handling code here:
        panelBanHang.setVisible(false);
        panelKho.setVisible(false);

        panelThongKe.setVisible(true);
    }//GEN-LAST:event_jbtnThongKeActionPerformed

    private void jbtnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDangXuatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Frame_Login frame_Login = new Frame_Login();
        frame_Login.setVisible(true);
    }//GEN-LAST:event_jbtnDangXuatActionPerformed

    private void jbtnKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKhoActionPerformed
        // TODO add your handling code here:
        panelBanHang.setVisible(false);
        panelThongKe.setVisible(false);

        panelKho.setVisible(true);
    }//GEN-LAST:event_jbtnKhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnBanHang;
    private javax.swing.JButton jbtnDangXuat;
    private javax.swing.JButton jbtnKho;
    private javax.swing.JButton jbtnThoat;
    private javax.swing.JButton jbtnThongKe;
    public static javax.swing.JLabel jlbNgayGio;
    public static javax.swing.JLabel jlbSoBanActive;
    private javax.swing.JLabel jlbTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
